libcontainer: remove redundant strings.Join()
opencontainers/runc pull request #2608
Opened 2020-09-29 09:49 UTC by thaJeztah

these looked quite redundant, and could be replaced by just concatenating the strings instead

2020-09-29 09:49 UTC, thaJeztah commented
@kolyshkin @AkihiroSuda ptal

2020-09-29 10:08 UTC, AkihiroSuda approved these changes

2020-09-30 16:26 UTC, kolyshkin requested changes
I'd rather leave `nsenter_test.go` as is, as in its current form it lets add more namespaces, and also serves as an example of how to use the functionality.

Other than that, LGTM

2020-09-30 21:24 UTC, thaJeztah commented
@kolyshkin reverted the changes in nsenter_test.go, PTAL

2020-10-01 01:13 UTC, kolyshkin approved these changes

2020-10-01 01:20 UTC, AkihiroSuda approved these changes

2020-10-01 01:20 UTC, merged