rootfs: handle github.com/moby/sys/mountinfo deficiency
opencontainers/runc pull request #2655
Opened 2020-10-21 07:11 UTC by cyphar

github.com/moby/sys/mountinfo doesn't fill the Root field of
mountinfo.Info when calling filter functions, meaning that the change in
commit b8bf57281298 ("rootfs: handle nested procfs mounts for MS_MOVE")
regressed the security hardening.

While this is being fixed upstream in [1], just remove this info.Root
optimisation because the ENOENT check is actually sufficient to fix the
original issue.

[1]: https://github.com/moby/sys/pull/50

Closes #2654
Reported-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

2020-10-21 07:35 UTC, AkihiroSuda approved these changes

2020-10-21 17:07 UTC, kolyshkin commented on tests/integration/no_pivot.bats
> +	[[ ${lines[*]} == *"mount: permission denied"* ]]
nit:
```suggestion
	[[ "$output" == *"mount: permission denied"* ]]
```

2020-10-21 17:07 UTC, kolyshkin requested changes
a nit in the test case, otherwise lgtm

2020-10-22 04:44 UTC, AkihiroSuda commented
closing as suggsted in https://github.com/opencontainers/runc/pull/2657#issuecomment-714022906

2020-10-22 04:44 UTC, closed without merging