cgroup: fix panic in parse memory.numa_stat
opencontainers/runc pull request #2751
Opened 2021-01-19 07:02 UTC by Ace-Tang

strings.SplitN not always return N fields if not staify, sometimes
cgroup interface add some custom fields make parse memory.numa_stat
fails, it will case panic

Signed-off-by: acetang <aceapril@126.com>

Fix panic in parse memory.numa_stat, since memory.numa_stat was add some custom fields that make splitN fail
![image](https://user-images.githubusercontent.com/10334997/104999077-34dd9400-5a67-11eb-99e2-f05b5b481265.png)

2021-01-19 07:09 UTC, AkihiroSuda commented on libcontainer/cgroups/fs/memory.go
> +			if len(pagesByNode) != 2 {
nit: s/2/numaStatColumnSliceLength/

2021-01-19 07:24 UTC, Ace-Tang commented on libcontainer/cgroups/fs/memory.go
> +			if len(pagesByNode) != 2 {
Update~

2021-01-19 07:28 UTC, AkihiroSuda approved these changes

2021-01-19 17:49 UTC, kolyshkin commented
@Ace-Tang can you show the contents of `memory.numa_stat` from that system?

For the record, here's kernel doc about memory.numa_stat (from https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt)

```
5.6 numa_stat

This is similar to numa_maps but operates on a per-memcg basis.  This is
useful for providing visibility into the numa locality information within
an memcg since the pages are allowed to be allocated from any physical
node.  One of the use cases is evaluating application performance by
combining this information with the application's CPU allocation.

Each memcg's numa_stat file includes "total", "file", "anon" and "unevictable"
per-node page counts including "hierarchical_<counter>" which sums up all
hierarchical children's values in addition to the memcg's own value.

The output format of memory.numa_stat is:

total=<total pages> N0=<node 0 pages> N1=<node 1 pages> ...
file=<total file pages> N0=<node 0 pages> N1=<node 1 pages> ...
anon=<total anon pages> N0=<node 0 pages> N1=<node 1 pages> ...
unevictable=<total anon pages> N0=<node 0 pages> N1=<node 1 pages> ...
hierarchical_<counter>=<counter pages> N0=<node 0 pages> N1=<node 1 pages> ...

The "total" count is sum of file + anon + unevictable.
```

The code was introduced by #2278, @iwankgb PTAL

2021-01-19 17:53 UTC, kolyshkin commented
On my (non-NUMA) system it's always 2 fields:
`find /sys/fs/cgroup/ -name memory.numa_stat | xargs awk '{print NF}' | grep -v ^2$`

2021-01-19 18:36 UTC, dqminh requested changes
The check is reasonable. However, it would be nice if we can add a failing test.

2021-01-20 06:35 UTC, Ace-Tang commented
The memory.numa_stat interface changes was add by other guys, but it was used online, althrough the interface develop not follow  kernel doc, fields is 
![image](https://user-images.githubusercontent.com/10334997/105136465-a6334a80-5b2c-11eb-9bd2-5497ec287dab.png)

@kolyshkin @dqminh

2021-01-20 21:21 UTC, kolyshkin commented
Ah, OK, I was not able to find these kernel patches in the wild -- the most similar one is "sched/numa: introduce per-cgroup NUMA locality info" from Alibaba's Michael Wang (which also adds some non-standard fields to `memory.numa_stat`). Another showcase of why text-based interfaces are not that good...

I took a look at the code and found that if someone ever adds some line that will contain `=` to `memory.numa_stat` file (e.g. `a=b`), the whole `GetStats` will return an error. Maybe it makes sense to make this code less fragile / more forgiving to unknown fields while we're at it. I'll look into it.

In the meantime, LGTM

2021-01-20 21:22 UTC, kolyshkin approved these changes
LGTM

2021-01-20 21:23 UTC, kolyshkin commented
@dqminh can we merge this hotfix as it is? I'm working on more robust parser and will add more tests.

2021-01-20 22:24 UTC, kolyshkin commented
> @dqminh can we merge this hotfix as it is? I'm working on more robust parser and will add more tests.

Alternatively, PTAL https://github.com/opencontainers/runc/pull/2755 which has this fix, and more fixes and tests.

2021-01-20 23:21 UTC, dqminh commented
@kolyshkin lets go with #2755 . Thanks @Ace-Tang very much for your fix !

2021-01-20 23:21 UTC, closed without merging

2021-01-21 01:56 UTC, Ace-Tang commented
Thanks