Fix typo in README
opencontainers/runc pull request #2771
Opened 2021-01-28 09:01 UTC by wangtianxia-sjtu

This fixes  a small typo in README.md.

[docs/terminals.md](runc terminal handling) -> [runc terminal handling](docs/terminals.md)

2021-01-28 21:12 UTC, kolyshkin approved these changes
LGTM, and thanks!

2021-01-28 21:13 UTC, kolyshkin requested changes
Commit needs to be signed, otherwise LGTM

2021-01-29 02:37 UTC, kolyshkin approved these changes
LGTM

2021-01-29 03:29 UTC, AkihiroSuda approved these changes

2021-01-29 03:29 UTC, merged