script/check-config.sh: add SELinux and AppArmor
opencontainers/runc pull request #2874
Opened 2021-03-26 11:27 UTC by KentaTada

SELinux and AppArmor are always enabled since runc v1.0.0-rc93

Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>

2021-03-26 17:53 UTC, kolyshkin requested changes
NACK. These should go in optional features. The fact that these are always enabled does not mean these are required -- it means these are supported.

2021-03-27 01:51 UTC, KentaTada commented
Thanks a lot.
I changed these options from necessary to optional features.

2021-03-27 06:16 UTC, AkihiroSuda approved these changes

2021-03-28 17:47 UTC, kolyshkin approved these changes
LGTM

2021-03-28 17:48 UTC, kolyshkin commented
CI failure is a flake (#2805); CI restarted

2021-03-29 20:45 UTC, merged