docs/terminals.md: add troubleshooting
opencontainers/runc pull request #2985
Opened 2021-06-02 02:22 UTC by kolyshkin

Explain where the "/dev/tty: no such device or address" error is coming
from, and provide ways to solve the issue.

For more background, see https://github.com/opencontainers/runc/issues/2970

2021-06-02 02:48 UTC, cyphar commented on docs/terminals.md
> +The solution to this is *not* use a terminal for the container, i.e. have
```suggestion
The solution to this is to *not* use a terminal for the container, i.e. have
```

2021-06-02 02:48 UTC, cyphar commented on docs/terminals.md
> +can happen in case stdin (and possibly also stdout and stderr) are redirected,
```suggestion
can happen when stdin (and possibly also stdout and stderr) are redirected,
```

2021-06-02 02:49 UTC, cyphar commented on docs/terminals.md
> +or on some environments that lack a tty (such as GitHub Actions runners).
```suggestion
or in some environments that lack a tty (such as GitHub Actions runners).
```

2021-06-02 02:49 UTC, cyphar commented on docs/terminals.md
> +The solution to this is *not* use a terminal for the container, i.e. have
```suggestion
The solution to this is to *not* use a terminal for the container, i.e. have
```

2021-06-02 02:49 UTC, cyphar commented on docs/terminals.md
> +(as some programs require it), you can provide one, using one of the following
```suggestion
(some programs require one), you can provide one, using one of the following
```

2021-06-02 02:50 UTC, cyphar commented on docs/terminals.md
> +One way to do so is to use `ssh -tt` option. The second `t` forces a terminal
```suggestion
One way is to use `ssh -tt`. The second `t` forces a terminal
```

2021-06-02 02:50 UTC, cyphar commented on docs/terminals.md
> +not a terminal (known `ssh` implementations only look for a terminal on stdin).
```suggestion
not a terminal (some `ssh` implementations only look for a terminal on stdin).
```

2021-06-02 02:51 UTC, cyphar commented on docs/terminals.md
> +Another way is to run runc under `script` utility, like this
```suggestion
Another way is to run runc under the `script` utility, like this
```

2021-06-02 02:52 UTC, cyphar commented on docs/terminals.md
> +Note that older versions of `script` are known to have issues.
Can you provide a bit more detail about what kinds of issues?

2021-06-02 02:55 UTC, cyphar requested changes

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +can happen in case stdin (and possibly also stdout and stderr) are redirected,
```suggestion
can happen when stdin (and possibly also stdout and stderr) are redirected,
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +or on some environments that lack a tty (such as GitHub Actions runners).
```suggestion
or in some environments that lack a tty (such as GitHub Actions runners).
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +The solution to this is *not* use a terminal for the container, i.e. have
```suggestion
The solution to this is to *not* use a terminal for the container, i.e. have
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +(as some programs require it), you can provide one, using one of the following
```suggestion
(some programs require one), you can provide one, using one of the following
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +One way to do so is to use `ssh -tt` option. The second `t` forces a terminal
```suggestion
One way is to use `ssh` with the `-tt` flag. The second `t` forces a terminal
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +not a terminal (known `ssh` implementations only look for a terminal on stdin).
```suggestion
not a terminal (some `ssh` implementations only look for a terminal on stdin).
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +Another way is to run runc under `script` utility, like this
```suggestion
Another way is to run runc under the `script` utility, like this
```

2021-06-02 02:55 UTC, cyphar commented on docs/terminals.md
> +Note that older versions of `script` are known to have issues.
Can you provide a bit more detail about what kinds of issues?

2021-06-02 16:36 UTC, kolyshkin commented
Addressed review comments, thanks @cyphar

2021-06-02 16:37 UTC, kolyshkin reviewed
Addressed review comments, thanks @cyphar

2021-06-02 16:39 UTC, kolyshkin commented
I'm not sure what's happening but it seems that GitHub comments system is having issues. I see review comments being repeated, and I don't see the replies that I left.

2021-06-02 20:27 UTC, kolyshkin commented
> Can you provide a bit more detail about what kinds of issues?

I think the biggest issue for me was that `script` from CentOS 7 always returned
exit code of 0, even if the program running in it was not. This made our tests
always succeed :) and was fixed in https://github.com/opencontainers/runc/pull/2745
(by replacing `script` with `ssh -tt`).

There was some occasional lockups as well, but I am not sure if this was script.
Looking into util-linux's git log for script sources, were were some races, so
maybe it was script.

Anyway, since this description is so vague, I have removed this "beware of bugs"
statement entirely.

2021-06-03 11:01 UTC, cyphar approved these changes
LGTM, thanks.

2021-06-03 17:13 UTC, mrunalp approved these changes

2021-06-03 17:13 UTC, merged