checkpoint: set default work-dir to image-path
opencontainers/runc pull request #3029
Opened 2021-06-15 02:50 UTC by liusdu

Sump/restrore logs are very useful when process fails.
So put them to image path defaultly，otherwise these files
will be deleted when container exits.

Signed-off-by: Liu Hua <weldonliu@tencent.com>

2021-06-15 03:39 UTC, kolyshkin commented
What prevents you from using `--work-path` instead of `--image-path` to achieve the same results? If `--image-path` is not set, it defaults to the value of `--work-path`, see https://criu.org/Directories).

Ahh I see -- standalone criu binary works as described above, but runc c/r doesn't.

I think we need to modify runc to NOT set `WorkDirectory` (and `CriuOpts.WorkDirFd`) if `--work-path` is not specified. This way `runc checkpoint` and `runc restore` will work the same way as `criu`, which I think is a sane way.

@liusdu can you implement the above?

2021-06-15 04:31 UTC, liusdu commented
> What prevents you from using `--work-path` instead of `--image-path` to achieve the same results? If `--image-path` is not set, it defaults to the value of `--work-path`, see https://criu.org/Directories).
Hi @kolyshkin, thanks to you reply.  if `--images-dir` is not set, it defaults to the value of "$(pwd)",  not  `--work-dir`. The description is as following:  
```
This is the one specified with the -D|--images-dir $path option. If not given CRIU uses current working directory.
```
And if `--work-dir` is not set, it defaults to the values to `--images-dir` see https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/crtools.c#L133

> 
> Ahh I see -- standalone criu binary works as described above, but runc c/r doesn't.
> 
> I think we need to modify runc to NOT set `WorkDirectory` (and `CriuOpts.WorkDirFd`) if `--work-path` is not specified. This way `runc checkpoint` and `runc restore` will work the same way as `criu`, which I think is a sane way.
> 
> @liusdu can you implement the above?

Yes, It can fix it this way~

2021-06-15 08:42 UTC, liusdu commented
@kolyshkin done, please take a look.

2021-06-15 09:15 UTC, kolyshkin commented
@liusdu needs a rebase

2021-06-15 10:30 UTC, liusdu commented
@kolyshkin  sorry for this, done~

2021-06-16 11:56 UTC, kolyshkin commented on libcontainer/container_linux.go
> +	// if criuOpts.WorkDirectory is not set. let criu sets it.
```suggestion
	// If criuOpts.WorkDirectory is not set, criu default is used
	// (which is to reuse ImagesDirectory as WorkDirectory).
```

2021-06-16 11:57 UTC, kolyshkin commented
I think you need to amend the commit message to explain how it works (i.e. by not setting the WorkDirectory we let criu use its default, which is to reuse ImagesDirectory, or some such).

2021-06-16 11:59 UTC, kolyshkin requested changes
A few typos in the commit message:

> Dump/restrore logs are very useful when process fails.

restore

> New runc puts these files in c.root, which will be deleted

I think you mean "Now".

> when container exits. So if checkpinting/restoring failed,

checkpointing

2021-06-16 19:03 UTC, kolyshkin approved these changes
LGTM

@adrianreber PTAL

2021-06-16 19:09 UTC, adrianreber commented
The only thing I am worried about is if Docker or Podman are relying on this somehow. Would be good to verify that neither of them break with this change.

2021-06-17 08:40 UTC, liusdu commented
@adrianreber Podman and  Docker/Containerd  all set  WorkDirectory.

1. Podman:
  - Code
  - behavior:
  
```
# restore command
podman  container restore  06fd1a24a1f0992c9349e7de45796b80e253a10fc1b7adcfc89052cd460a4288
# output
Error: OCI runtime error: criu failed: type NOTIFY errno 0
log file: /var/lib/containers/storage/overlay-containers/06fd1a24a1f0992c9349e7de45796b80e253a10fc1b7adcfc89052cd460a4288/userdata/restore.log
# restore.log is perisist on disk
ls -l /var/lib/containers/storage/overlay-containers/06fd1a24a1f0992c9349e7de45796b80e253a10fc1b7adcfc89052cd460a4288/userdata/restore.log 
-rw------- 1 root root 25921 6月  17 11:03 /var/lib/containers/storage/overlay-containers/06fd1a24a1f0992c9349e7de45796b80e253a10fc1b7adcfc89052cd460a4288/userdata/restore.log
```

2. Containerd:

2021-06-18 15:32 UTC, adrianreber commented
Thanks for looking into it. So Docker and Podman both seem to always set WorkDirectores and ImagesDirectory.

This PR should  not lead to different behaviour on the container engine level.

Patch LGTM

2021-06-25 02:44 UTC, mrunalp approved these changes
LGTM

2021-06-25 02:44 UTC, merged