libct/cg/sd: simplify DetectUserDbusSessionBusAddress
opencontainers/runc pull request #3356
Opened 2022-01-28 02:29 UTC by kolyshkin

Apparently, `systemctl --user --no-pager show-environment` is useless
without `DBUS_SESSION_BUS_ADDRESS` or `XDG_RUNTIME_DIR` set:

	$ echo $DBUS_SESSION_BUS_ADDRESS, $XDG_RUNTIME_DIR
	unix:path=/run/user/1000/bus, /run/user/1000
	$ systemctl --user --no-pager show-environment | grep DBUS_SESS
	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
	$ unset DBUS_SESSION_BUS_ADDRESS
	$ systemctl --user --no-pager show-environment | grep DBUS_SESS
	DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
	$ unset XDG_RUNTIME_DIR
	$ systemctl --user --no-pager show-environment | grep DBUS_SESS
	Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)

So, it does not make sense to try it to get the address.

Also, it does not make sense to try `systemctl --user start dbus`
either, for the same reason, so remove that suggestion from the error
message text. Since `DBUS_SESSION_BUS_ADDRESS` environment variable
is set by dbus-run-session (or dbus-launch, or something similar that is
supposed to be run during the login process), add a suggestion to
re-login.

2022-01-28 03:50 UTC, AkihiroSuda commented on libcontainer/cgroups/systemd/user.go
>  		}
When `$DBUS_SESSION_BUS_ADDRESS` is unset but `$XDG_RUNTIME_DIR` is set, probably we can try `systemctl --user --no-pager show-environment`

2022-01-28 03:53 UTC, AkihiroSuda requested changes
`systemctl --user show-environment` is for covering `$XDG_RUNTIME_DIR is set but $XDG_RUNTIME_DIR/bus does not exist` case, not for covering `$XDG_RUNTIME_DIR is unset` case

2022-01-28 04:39 UTC, kolyshkin commented
> `systemctl --user show-environment` is for covering `$XDG_RUNTIME_DIR is set but $XDG_RUNTIME_DIR/bus does not exist` case, not for covering `$XDG_RUNTIME_DIR is unset` case

Right, I missed that path.

However, current version of systemd does the same thing as we do -- it tries "unix:path=%s/bus", where `%s` is the value of `XDG_RUNTIME_DIR`. 

Here's the logic:
https://github.com/systemd/systemd/blob/be7148ebed5d73c4a76bc6089ebe2e82d8fa33e0/src/libsystemd/sd-bus/sd-bus.c#L1332-L1347

The only caveat is it uses `bus_address_escape` function:
https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/libsystemd/sd-bus/bus-internal.c#L294-L318

Will take a look into it.

2022-02-01 02:55 UTC, kolyshkin commented
> The only caveat is it uses bus_address_escape function:
https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/libsystemd/sd-bus/bus-internal.c#L294-L318
>
> Will take a look into it.

It seems that if we are re-creating DBUS_SESSION_BUS_ADDRESS from XDG_RUNTIME_DIR, we need to escape some characters, same as what `bus_address_escape` function in systemd does:
https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/libsystemd/sd-bus/bus-internal.c#L294-L318.

Once that is done, we can remove the fallback which this PR removes.

Changing to draft for now.

2022-02-01 22:00 UTC, kolyshkin commented
OK, I have added proper address value escaping, so now our fallback is the same as systemd's (see previous comments).

@AkihiroSuda PTAL

2022-02-01 22:09 UTC, kolyshkin commented
> > `systemctl --user show-environment` is for covering `$XDG_RUNTIME_DIR is set but $XDG_RUNTIME_DIR/bus does not exist` case, not for covering `$XDG_RUNTIME_DIR is unset` case
> 
> Right, I missed that path.
> 
> However, current version of systemd does the same thing as we do -- it tries "unix:path=%s/bus", where `%s` is the value of `XDG_RUNTIME_DIR`.

In other words,
 - if `XDG_RUNTIME_DIR` is set, and `$XDG_RUNTIME_DIR/bus` exists, our code will use it and won't fall back to calling `systemctl`;
 - if `XDG_RUNTIME_DIR` is not set, or `$XDG_RUNTIME_DIR/bus` does not exist (ot can't be connected to), `systemctl --user` can not be used at all, as it needs a dbus connection.
 
Therefore,
 - a fallback of using systemctl is useless, as it will fail anyway.
 - suggesting to try `systemctl --user start dbus` in error message is useless, too, as it will fail anyway.

2022-02-16 03:42 UTC, AkihiroSuda submitted a review, later dismissed

2022-03-01 19:40 UTC, kolyshkin commented
Removed the dbus bump commit as it is now obsoleted by #3398.

@AkihiroSuda @thaJeztah PTAL

2022-03-02 01:39 UTC, AkihiroSuda approved these changes

2022-03-09 01:54 UTC, kolyshkin commented
@thaJeztah @cyphar @mrunalp PTAL

2022-03-09 16:35 UTC, thaJeztah approved these changes
LGTM

2022-03-09 16:36 UTC, merged