Pin actions to a full length commit SHA
opencontainers/runc pull request #3431
Opened 2022-03-24 02:38 UTC by naveensrinivasan

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

>Pin actions to a full length commit SHA

>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Also, dependabot supports upgrading based on SHA.

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

2022-03-24 05:01 UTC, AkihiroSuda submitted a review, later dismissed

2022-03-27 01:28 UTC, kolyshkin requested changes
Can we at least not do that with "offical" actions? I mean, if GitHub itself is a bad actor, we are doomed anyway...

2022-03-27 16:46 UTC, naveensrinivasan commented
> Can we at least not do that with "offical" actions? I mean, if GitHub itself is a bad actor, we are doomed anyway...

I have changed that not to pin the official GitHub actions and I have also included the comment with the URL for someone to validate each of the SHA's.

2022-04-09 01:23 UTC, kolyshkin commented
@naveensrinivasan I don't understand the need for the second commit.

2022-04-09 01:27 UTC, naveensrinivasan commented
I thought the URL would help understand what the SHA's point to.

2022-04-09 01:28 UTC, kolyshkin commented
> I thought the URL would help understand what the SHA's point to.

I mean this commit: 
https://github.com/opencontainers/runc/pull/3431/commits/bc5fd3f3c778ce6a190675984ced909890c6955a

2022-04-09 23:56 UTC, naveensrinivasan commented
> > I thought the URL would help understand what the SHA's point to.
> 
> I mean this commit: [bc5fd3f](https://github.com/opencontainers/runc/commit/bc5fd3f3c778ce6a190675984ced909890c6955a)

I agree. That shouldn't have been part of this. Would you want me to remove this? Let me know. Thanks

2022-08-04 23:10 UTC, kolyshkin commented
The second commit is obsoleted by #3445. The first one, I'm not sure we want it at all.

2022-08-04 23:10 UTC, closed without merging