libct/nsenter: remove kill()
opencontainers/runc pull request #3501
Opened 2022-06-05 16:59 UTC by jellor

kill(stage2_pid, SIGKILL) maybe will kill all processes except the process itself and init when the stage2_pid equals -1.

Signed-off-by: Guodong Zhu <guodong9211@gmail.com>

2022-06-07 00:05 UTC, cyphar commented
We shouldn't reach those `kill` sections if the pid is -1, but even if that was something that happened the correct patch would check for `pid <= 0` rather than removing the kill calls. It is necessary to send a kill signal in these cases because we don't want the child process to stay alive if there is an issue during setup (we can't use `PDEATHSIG` since we use `CLONE_PARENT`).

2022-06-07 00:07 UTC, cyphar requested changes
We shouldn't reach those `kill` sections if the pid is -1, but even if that was something that happened the correct patch would be to switch all of the `kill` calls to `sane_kill` (which checks for `pid >= 0`) rather than removing the `kill` calls. It is necessary to send a kill signal in these cases because we don't want the child process to stay alive if there is an issue during setup (we can't use `PDEATHSIG` since we use `CLONE_PARENT`).

2022-06-11 04:01 UTC, jellor commented
> @jellor do you have some kind of a repro?

@kolyshkin One case like using BCC script (https://gist.github.com/jellor/1f2fe1147ca63c031d729dfdd2ede065) to override `write(SYNC_MOUNTSOURCES_PLS)` return value, then it will reach `kill(stage2_pid = -1, SIGKILL)` call. NB: it can send SIGKILL to every process but except the process itself and init.

> We shouldn't reach those `kill` sections if the pid is -1, but even if that was something that happened the correct patch would be to switch all of the `kill` calls to `sane_kill` (which checks for `pid >= 0`) rather than removing the `kill` calls. It is necessary to send a kill signal in these cases because we don't want the child process to stay alive if there is an issue during setup (we can't use `PDEATHSIG` since we use `CLONE_PARENT`).

Yes, switch `kill` calls to `sane_kill`  (which checks for `pid > 0`) can resolve this issue.

2022-06-11 16:32 UTC, kolyshkin commented
Commit subject (and PR subject) should be modified accordingly (`s/remove kill/switch to sane_kill/` or something like that).

2022-06-26 16:41 UTC, jellor commented
@cyphar PTAL, thanks!

2022-06-26 16:43 UTC, jellor commented
@kolyshkin What should I need to do?

2022-06-27 05:40 UTC, cyphar approved these changes
LGTM.

2022-06-27 05:42 UTC, cyphar commented
@jellor  You create a PR against `release-1.1` with the patch cherry-picked (`git cherry-pick`).

2022-06-27 05:45 UTC, cyphar commented
> One case like using BCC script (https://gist.github.com/jellor/1f2fe1147ca63c031d729dfdd2ede065) to override write(SYNC_MOUNTSOURCES_PLS) return value, then it will reach kill(stage2_pid = -1, SIGKILL) call

While I'm fine with this patch (since `sane_kill` is the reasonable thing to do anyway), I highly doubt it's actually possible for the `write` to fail in practice because it's a small write on a pipe.

2022-06-27 08:26 UTC, merged