Fix error from runc run on noexec fs
opencontainers/runc pull request #3522
Opened 2022-06-30 20:07 UTC by kolyshkin

When starting a new container, and the very last step of executing of a
user process fails (last lines of `(*linuxStandardInit).Init)`, it is too
late to print a proper error since both the log pipe and the init pipe
are closed.

This is partially mitigated by using exec.LookPath() which is supposed
to say whether we will be able to execute or not. Alas, it fails to do
so when the binary to be executed resides on a filesystem mounted with
noexec flag.

A workaround is to use access(2) with X_OK flag.

Fixes https://github.com/opencontainers/runc/issues/3520

2022-06-30 20:20 UTC, kolyshkin commented
@opencontainers/runc-maintainers do we ever use `runc` as a setuid or setgid binary? If yes, this commit will break it, since `access(2)` checks the real, not effective, uid/gid, and we need AT_EACCESS (which is actually only supported since linux v5.8 or so).

2022-07-01 01:53 UTC, AkihiroSuda requested changes
Sorry NOTLGTM, as potentially somebody might be using runc with setuid bit

(I know colima and Rancher Desktop launch nerdctl with setuid bit. AFAICS they do not launch runc with setuid bit, but I assume there are some similar projects and some of them may launch runc with setuid bit)

2022-07-01 16:42 UTC, kolyshkin commented
> (I know colima and Rancher Desktop launch nerdctl with setuid bit. AFAICS they do not launch runc with setuid bit, but I assume there are some similar projects and some of them may launch runc with setuid bit)

Thanks! I explained above this is not a problem -- we just need a more complex check for this case.

Working on it.

2022-07-01 17:06 UTC, kolyshkin commented
@AkihiroSuda added suid runc support; PTAL

2022-07-01 22:42 UTC, AkihiroSuda approved these changes

2022-07-02 13:20 UTC, thaJeztah approved these changes
SGTM

do we need more eyes on this?

2022-07-15 01:55 UTC, AkihiroSuda commented
@cyphar LGTY?

2022-08-02 02:39 UTC, cyphar approved these changes
LGTM.

2022-08-02 02:41 UTC, merged

2023-02-08 21:38 UTC, AkihiroSuda commented
Can we revert this?

For
- https://github.com/opencontainers/runc/issues/3715

2023-02-09 06:19 UTC, kolyshkin commented
@AkihiroSuda from what I see, we need to add a check for CAP_DAC_OVERRIDE -- it it is set, than the lack of x bit can be ignored. I will look at it tomorrow.