Fix runc crushes when parsing invalid JSON specification file
opencontainers/runc pull request #3728
Opened 2023-02-07 07:56 UTC by AITsygunka

Fixes [#3727](https://github.com/opencontainers/runc/issues/3727#issue-1573797885)

2023-02-07 21:46 UTC, cyphar commented on spec.go
>  	}
```suggestion
	if err = json.NewDecoder(cf).Decode(&spec); err != nil || spec == nil {
		return nil, err
	} else if spec == nil {
		return nil, fmt.Errorf("config cannot be null")
	}
```

It should be noted the issue here is not with invalid JSON (that would return an error from `json.Decode`), but instead with a `config.json` that is set to `null` (which is valid JSON). I feel like another option would be to have `spec` be `specs.Spec` which would stop it from being able to be `nil`.

2023-02-07 21:46 UTC, cyphar commented
You need to add a `Signed-off-by:` line to your commit(s) which indicates that you attest the [Developer Certificate of Origin](https://developercertificate.org/) a statement about your contributions that you *must read* before signing (don't worry, it's quite short and easy-to-read). You can add it to your commits with `git commit --amend -s`, and then doing a `git push --force`.

###### **NOTE**: This is a saved reply. Sorry if it reads as a cookie-cutter response, it was written so that newcomers understand what a "DCO" is and make the process for contributing a little less scary. ######

2023-02-09 22:09 UTC, kolyshkin commented on spec.go
> +	} else if spec == nil {
`else` is redundant here because of the return statement above it.

2023-02-09 22:10 UTC, kolyshkin requested changes

2023-02-09 22:10 UTC, kolyshkin commented on spec.go
> +		return nil, fmt.Errorf("config cannot be null")
Nit: hen there are no %-style arguments, `errors.New` is better.

2023-02-10 22:43 UTC, kolyshkin submitted a review, later dismissed
LGTM

2023-02-10 22:49 UTC, kolyshkin commented
CI failure is unrelated; it was recently reported as #3742

2023-02-16 01:50 UTC, kolyshkin commented
@AITsygunka please rebase to fix CI

2023-02-22 04:20 UTC, AkihiroSuda approved these changes

2023-02-22 10:57 UTC, kolyshkin approved these changes
LGTM

2023-02-22 10:57 UTC, merged