[1.1] libctr/cgroups: don't take init's cgroup into account
opencontainers/runc pull request #3811
Opened 2023-04-04 18:52 UTC by haircommander

Sometimes, the init process is not in the root cgroup. This can be noted by GetInitPath, which already scrubs the path of `init.scope`.

This was encountered when trying to patch the Kubelet to handle systemd being in a separate cpuset from root (to allow load balance disabling for containers). At present, there's no way to have libcontainer or runc manage cgroups in a hierarchy outside of the one init is in (unless the path contains `init.scope`, which is limiting)

2023-04-04 18:56 UTC, haircommander commented
PTAL @kolyshkin @mrunalp

2023-04-04 22:06 UTC, kolyshkin commented
To reviewers: this is a backport of PR #3784 to release-1.1 branch. In comments to that PR, I tried to find out whether this change can break anything. TL;DR, my conclusion was (and still is) that this is not a breaking change. More to say, using PID 1's cgroup as a base is not correct when host pid ns is used, and thus it was removed a long time ago (but not for systemd cgroup driver).

Now, this PR is required for the case where systemd is placed into a non-root cgroup.

Such placement is needed in recent kernels, when we want some containers (cgroups) to have CPU load-balancing disabled (`cpuset.sched_load_balance = 0`). Unfortunately, this also requires all the cgroup parents (up to root cgroup) to also have LB disabled. So, in order to achieve this without disabling CPU load balancing systemd-wide, all other processes on the system (including systemd) are moved to a separate cgroup hierarchy.

2023-04-04 22:07 UTC, kolyshkin submitted a review, later dismissed
LGTM

2023-04-05 16:04 UTC, mrunalp approved these changes

2023-04-06 04:28 UTC, AkihiroSuda commented
DCO check is failing

2023-04-06 14:02 UTC, haircommander commented
fixed!

2023-04-06 22:57 UTC, kolyshkin submitted a review, later dismissed
Still LGTM

2023-04-06 23:01 UTC, mrunalp approved these changes

2023-04-07 01:40 UTC, kolyshkin approved these changes
still LGTM

2023-04-07 01:56 UTC, mrunalp approved these changes

2023-04-07 02:39 UTC, AkihiroSuda requested changes
Please use `git cherry-pick` with `-x`

2023-04-07 13:42 UTC, haircommander commented
> Please use git cherry-pick with -x


done!

2023-04-07 13:43 UTC, AkihiroSuda approved these changes
Thanks

2023-04-07 15:05 UTC, merged