Backport riscv64 support into 1.1.x
opencontainers/runc pull request #3905
Opened 2023-06-16 10:14 UTC by chazapis

This is necessary for [running on RISC-V using K3s](https://github.com/k3s-io/k3s/pull/7778).

Many projects - including K3s - depend on runc 1.1.x, so waiting for a 2.0.x release and then porting to any changes introduced may probably be a much larger effort. This includes all changes done in #3446, which are really minimal but necessary to support the new architecture.

With this patch I have successfully compiled and run K3s on a RISC-V QEMU VM and have verified that I can create Pods.

2023-06-16 17:16 UTC, AkihiroSuda requested changes
Please use `git cherry-pick -x`

2023-06-17 15:30 UTC, chazapis commented
> Please use `git cherry-pick -x`

Done.

2023-06-17 15:56 UTC, AkihiroSuda approved these changes

2023-06-21 18:17 UTC, kolyshkin approved these changes
LGTM

2023-06-28 13:27 UTC, AkihiroSuda commented
Please rebase

2023-06-28 21:00 UTC, chazapis commented
> Please rebase

Done.

2023-06-28 22:49 UTC, AkihiroSuda approved these changes

2023-06-28 22:49 UTC, merged

2025-02-05 09:04 UTC, thaJeztah commented
Looks like this PR introduced a regression, and missed the follow-up fix from; 

- https://github.com/opencontainers/runc/pull/3746

```patch
-		LDFLAGS_STATIC := -linkmode external -extldflags --static-pie
+		LDFLAGS_STATIC := -linkmode external -extldflags -static-pie
```