Code refactor: remove a function scope variable err for psi stats
opencontainers/runc pull request #3938
Opened 2023-07-14 01:38 UTC by lifubang

Address https://github.com/opencontainers/runc/pull/3900#discussion_r1262794812

I think it's unnecessary to add a function scope variable suddenly. We should keep the code style like other cgroup stats.

2023-07-15 02:01 UTC, lifubang commented
ci lint error:
```
Run golangci-lint run --config .golangci-extra.yml --new-from-rev=HEAD~1 --out-format=github-actions
  golangci-lint run --config .golangci-extra.yml --new-from-rev=HEAD~1 --out-format=github-actions
  shell: /usr/bin/bash -e {0}
  env:
    GO_VERSION: 1.[2](https://github.com/opencontainers/runc/actions/runs/5549548107/jobs/10133764716?pr=3938#step:6:2)0.x
Warning: var-naming: func statCpuPressure should be statCPUPressure (revive)
Error: Process completed with exit code 1.
```
The `Extra linters` are only checking new code from a pull request, it never check the old code, for example: `isCpuSet`, `setCpu`, and `statCpu`.
Shall we need to modify the old code to fit the extra linters in the same file? @thaJeztah @kolyshkin 
I think the issue #3936 may facing the same problem.

2023-07-18 00:41 UTC, kolyshkin commented on libcontainer/cgroups/fs2/cpu.go
> +	const file = "cpu.pressure"
I would pass "cpu.pressure" directly, without adding an intermediary `const`. The `const` would make sense if we use it more than once, or if the value is complicated/long -- neither is the case here.

2023-07-18 00:43 UTC, kolyshkin commented
I'm neutral on this.
* pro: `GetStats` looks more uniform now
* contra: more code is added

Left a nit about using consts for file names, but overall LGTM

2023-07-18 00:45 UTC, kolyshkin commented
Re: linter, I think we can start naming things better (`CPU` not `Cpu`) in any new code (and also maybe rename the existing ones), but this is minor. Feel free to add `//nolint:revive` if you don't want to stick to what revive tells you.

@thaJeztah WDYT?

2024-07-02 23:55 UTC, kolyshkin commented on libcontainer/cgroups/fs2/io.go
> +}
I'd rewrite this one to
```go
func statIoPressure(dirPath string, stats *cgroups.Stats) (Err error) {
	stats.BlkioStats.PSI, Err = statPSI(dirPath, "io.pressure")
	return
}
```

2024-07-02 23:56 UTC, kolyshkin commented on libcontainer/cgroups/fs2/io.go
> +}
but with this rewrite, it doesn't make much sense to have it as a separate function, right?

2024-07-02 23:57 UTC, kolyshkin requested changes
I don't think this makes the code much better than it is.

2024-07-02 23:57 UTC, closed without merging