[RFC] build: add build tag to disable eBPF
opencontainers/runc pull request #4005
Opened 2023-09-01 13:05 UTC by giuseppe

we are using runc to read the cgroup configuration, if eBPF is enabled it pulls in the cilium/ebpf dependency that increases the binary size by ~1 MB.

2023-09-01 14:17 UTC, giuseppe commented
@AkihiroSuda @kolyshkin what do you think about this flag?

2023-09-01 14:51 UTC, AkihiroSuda commented
Sorry, NACK, as eBPF is a hard dependency for cgroup v2 (in the initial UserNS)

2023-09-01 14:53 UTC, AkihiroSuda commented
For library use, the packages should be just split and refactored to eliminate eBPF deps

2023-09-01 14:54 UTC, AkihiroSuda requested changes
NACK, please see my comments above

2023-09-01 15:06 UTC, giuseppe commented
> For library use, the packages should be just split and refactored to eliminate eBPF deps

how do you suggest splitting it?

2023-09-01 17:25 UTC, kolyshkin commented
@giuseppe this is already solved last year in #3452 (in a way described by @AkihiroSuda above). So you can try using runc from HEAD and seeing if it helps with the bloat.

The only problem is, we haven't made a release having it yet. Working on it.

2023-09-01 21:12 UTC, giuseppe commented
> @giuseppe this is already solved last year in #3452 (in a way described by @AkihiroSuda above). So you can try using runc from HEAD and seeing if it helps with the bloat.
> 
> The only problem is, we haven't made a release having it yet. Working on it.

I've tried with the latest runc from HEAD but I still get the ebpf dependency, and as a result the podman binary is ~1MB bigger.  I'll check better if I am doing anything wrong, but I cannot see any import of `github.com/opencontainers/runc/libcontainer/cgroups/devices`:

```
$ go mod why github.com/opencontainers/runc/libcontainer/cgroups/devices
# github.com/opencontainers/runc/libcontainer/cgroups/devices
(main module does not need package github.com/opencontainers/runc/libcontainer/cgroups/devices)
```

2023-09-01 21:29 UTC, giuseppe commented
I'll close this PR and investigate better the proposed way

2023-09-01 21:29 UTC, closed without merging

2023-11-03 08:22 UTC, giuseppe commented
> The only problem is, we haven't made a release having it yet. Working on it.

sadly the last release did not fix the issue I have reported.  It is enough to pull `github.com/opencontainers/runc/libcontainer/cgroups/fs` and it will add the dependency on `/devices` and eBPF:

```
$ go mod why github.com/opencontainers/runc/libcontainer/cgroups/devices
# github.com/opencontainers/runc/libcontainer/cgroups/devices
github.com/containers/podman/v4/cmd/podman/containers
github.com/containers/common/pkg/cgroups
github.com/opencontainers/runc/libcontainer/cgroups/fs
github.com/opencontainers/runc/libcontainer/cgroups/devices
```