Update feature status in docs
opencontainers/runc pull request #4035
Opened 2023-09-26 19:31 UTC by Zheaoli

Signed-off-by: Manjusaka <me@manjusaka.me>

2023-09-26 20:23 UTC, AkihiroSuda approved these changes

2023-09-27 01:03 UTC, kolyshkin requested changes
I would like the commit message to be something like

```
Subject: docs/spec-conformance: update

Since PR 3876 was merged, let's remove time namespace from the list of unimplemented features.
```

2023-09-27 04:54 UTC, lifubang approved these changes
LGTM, thanks.

2023-09-27 17:34 UTC, kolyshkin approved these changes
LGTM

2023-09-27 17:34 UTC, merged