logs.go: fixed logger creation
opencontainers/runc pull request #4254
Opened 2024-04-25 10:43 UTC by AntonMoryakov

Previously, the done channel was not closed properly in case of an error returned by logPipe.Close(), potentially leading to a goroutine leak. This commit ensures that the done channel is closed even if there's an error during the closing of logPipe.

2024-04-25 15:15 UTC, kolyshkin approved these changes
LGTM

Wonder how have you found this @AntonMoryakov ?

2024-04-26 01:12 UTC, lifubang commented
> the done channel was not closed properly in case of an error returned by logPipe.Close()

I think we have catched the error returned by `logPipe.Close()`, so I think the done channel will be closed in any case.
https://github.com/opencontainers/runc/blob/71524dcff4f824772f6b64df6b29a7903ac0781d/libcontainer/logs/logs.go#L30-L32

Yes, but I think it will be better to move it to defer func. Thanks.

2024-04-26 01:50 UTC, kolyshkin commented
> > the done channel was not closed properly in case of an error returned by logPipe.Close()
> 
> I think we have catched the error returned by `logPipe.Close()`, so I think the done channel will be closed in any case.
> 
> https://github.com/opencontainers/runc/blob/71524dcff4f824772f6b64df6b29a7903ac0781d/libcontainer/logs/logs.go#L30-L32

Hmm you are right (not sure how I overlooked it).

So, while `defer` is indeed better, there's nothing to fix here. For this reason, I'd rather not merge this.

2024-04-26 01:51 UTC, kolyshkin requested changes
As pointed out above, there's nothing to fix here.

Or, at the very least, the description needs to be changed.

2024-05-09 20:31 UTC, kolyshkin commented
@AntonMoryakov can you comment on https://github.com/opencontainers/runc/pull/4254#issuecomment-2078454118?

2024-05-09 20:32 UTC, kolyshkin commented
Closing for now; will reopen depending on the PR author response.

2024-05-09 20:32 UTC, closed without merging