ci: revert #4020
opencontainers/runc pull request #4446
Opened 2024-10-15 08:55 UTC by lifubang

we need (#4020) because of (#3931), at that time, we removed the bindfd logic, and the
memfd logic will use more memory than before, but we have not yet moved binary clone from
runc init to runc parent process, so we need to increase memory limit in CI.
As we have moved the runc binary clone logic from runc init to runc parent process in
(#3987), so the memory usage of binary clone will not be included in container's memory
cgroup accounting. Now we can support run a simple container with lower memory usage the
same as before.

Signed-off-by: lifubang <lifubang@acmcoder.com>

2024-10-15 14:39 UTC, rata approved these changes
LGTM

2024-10-15 19:42 UTC, kolyshkin reviewed
Can you please refer to commits (rather than PRs) in commit messages? It is way easier to follow this way.

2024-10-15 23:00 UTC, lifubang commented
> It looks like this PR also silently reverts part of commit [3083bd4](https://github.com/opencontainers/runc/commit/3083bd443f7b37929f9a83165e365a597d2c6d71). Why?

Good catch, there were some conflicts need to resolve, we need to care the both commits, not just the commit in #4020.
Fixed.

2024-10-18 00:54 UTC, kolyshkin approved these changes
LGTM, thanks!

2024-10-18 01:11 UTC, kolyshkin commented
Need to fix EL9 CI first (see #4455).

2024-10-18 06:07 UTC, lifubang commented
> Need to fix EL9 CI first (see #4455).

When I re-run the failure CI, it is suddenly green now!

2024-10-21 01:53 UTC, kolyshkin commented
> Can you please refer to commits (rather than PRs) in commit messages? It is way easier to follow this way.

@lifubang please ^^^

2024-10-21 01:54 UTC, kolyshkin requested changes
Needs commit IDs not PRs in commit message

2024-10-21 08:35 UTC, cyphar approved these changes

2024-10-21 08:58 UTC, merged